### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by ishandutta2007** [fredrik-johansson/python-flint#23] opened 2022-06-06 14:08 UTC
`pip install python-flint`

```
Collecting python-flint
  Using cached python-flint-0.3.0.tar.gz (109 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hp\AppData\Local\Temp\pip-install-t78e2ife\python-flint_d406613e5b5443578ec37b8456cf9fce\setup.py", line 12, in <module>
          os.environ['OPT'] = " ".join(flag for flag in opt.split() if flag != '-Wstrict-prototypes')
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by arosen93** [comment] 2022-06-21 23:31
Seconding this for Windows 10.

**Comment by arosen93** [comment] 2022-06-21 23:50
Looks like this can be solved if you use the Anaconda build: `conda install -c conda-forge python-flint`.

**Comment by oscarbenjamin** [comment] 2022-06-22 00:16
For now `pip install python-flint` is unlikely to work. It will work if:

1. You have flint and all the other associated C libraries installed and configured with the appropriate paths.
2. You have a supported C compiler installed.
3. You have Python plus the dev headers installed.

Unless you go out of your way to set all of that up then `pip install` will fail. There has been some progress towards making wheels for Linux and OSX but not Windows.

In the meantime it is best to use conda unless you want to build this yourself (which is not actually that difficult on Ubuntu).

**Comment by oscarbenjamin** [comment] 2022-12-03 14:29
I'm going to close this as a duplicate of #1.

**Closed by oscarbenjamin** 2022-12-03 14:29 UTC

**Comment by azamatnarzuloyev** [comment] 2023-03-22 10:03
C:\Users\HOME\AppData\Local\Temp\pip-install-llrq34pb\python-flint_b6b8de5c84a548518c1f121e2940c620\setup.py:7: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        from numpy.distutils.system_info import default_include_dirs, default_lib_dirs
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HOME\AppData\Local\Temp\pip-install-llrq34pb\python-flint_b6b8de5c84a548518c1f121e2940c620\setup.py", line 12, in <module>
          os.environ['OPT'] = " ".join(flag for flag in opt.split() if flag != '-Wstrict-prototypes')
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by azamatnarzuloyev** [comment] 2023-03-22 10:04
I have the same error please help
